# Generated by Django 4.0.4 on 2023-01-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodmaster_table',
            fields=[
                ('food_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=30)),
                ('qty', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('discription', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'foodmaster_table',
            },
        ),
        migrations.AddField(
            model_name='id_gen',
            name='foodM_id',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
