# Generated by Django 4.0.4 on 2023-01-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_foodmaster_table_id_gen_foodm_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=90)),
                ('category', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'loging_table',
            },
        ),
    ]
