# Generated by Django 4.0.4 on 2023-01-18 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_id_gen_staf_id_staf_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staf_table',
            name='angan_id',
        ),
    ]
