# Generated by Django 4.0.4 on 2023-01-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_staf_table_id_angan'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_gen',
            name='student_id',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
