# Generated by Django 4.0.4 on 2023-01-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_women_table_id_gen_prg_women_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='women_table',
            name='phone',
            field=models.CharField(default='0', max_length=30),
            preserve_default=False,
        ),
    ]
