# Generated by Django 4.0.4 on 2023-02-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_notification_table_an_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_gen',
            name='allot_id',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
