# Generated by Django 4.0.4 on 2023-02-23 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_id_gen_allot_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodallotment_table',
            fields=[
                ('allot_num', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('angwadi_id', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('month', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('allot_dt', models.CharField(max_length=30)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.foodmaster_table')),
            ],
            options={
                'db_table': 'foodallotment_table',
            },
        ),
    ]
