# Generated by Django 4.0.4 on 2023-02-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_id_gen_compl_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmpl_id', models.CharField(max_length=90)),
                ('complaint', models.CharField(max_length=90)),
                ('comp_dt', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'complaint_table',
            },
        ),
    ]
